resolver: lts-15.5

packages:
  - .

extra-deps:
  - type-level-sets-0.8.9.0
  - bindings-libusb-1.4.5.0
  - usb-1.3.0.6
  - git: https://github.com/fumieval/mason.git
    commit: 7251b09b2b8c0ca9e8d59b90a1154742f149d87f
    #nix-sha256: 0bf5141sk0lrwri21s59gd4659cxqbhygw75dzph9gbhjkvm7aya
  - git: https://github.com/Philonous/hexquote
    commit: 61777223576644185689f2303684644acfd67d24
    #nix-sha256: 0lf2bxhd4hyls057wgmlgdagav7y5b9d54pqv6i0msjjlyx6kpw3

