resolver: lts-15.8

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai
packages:
  - .

extra-deps:
  - git: https://github.com/fumieval/mason.git
    commit: 7251b09b2b8c0ca9e8d59b90a1154742f149d87f
    #nix-sha256: 0bf5141sk0lrwri21s59gd4659cxqbhygw75dzph9gbhjkvm7aya
  - git: https://github.com/Philonous/hexquote
    commit: 61777223576644185689f2303684644acfd67d24
    #nix-sha256: 0lf2bxhd4hyls057wgmlgdagav7y5b9d54pqv6i0msjjlyx6kpw3

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=2.1"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
